on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

jobs:
  update-release-trigger-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-automation-bots
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
        with:
          fetch-depth: 1
          ref: rt-lock-hashes
          repository: googleapis/repo-automation-bots
      - name: Setup Python
        uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9 # v4
        with:
          python-version: 3.8
      - name: Update lockfile
        run: |
          cd packages/release-trigger
          pip install pip-tools
          pip-compile --generate-hashes requirements.in
      - name: Open pull request
        uses: googleapis/code-suggester@4341110e329c511a31b6af610930a8d885106aea # v4
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: pr
          upstream_owner: googleapis
          upstream_rep: repo-automation-bots
          description: Updates pip lockfile with latest releasetool version
          title: 'fix(deps): update releasetool'
          message: 'fix(deps): update releasetool'
          branch: update-releasetool
          primary: rt-lock-hashes
          git_dir: '.'
